name: Nightly
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.5
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0

      - name: Build ğŸ”§
        run: python3 build_plugin.py --out-dir dist dw235nightly "plugins/*.js"

      - name: PreRelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          target_commitish: dev
          prerelease: true
          files: dist/*.js
